### PR TITLE
Added some article links and removed https://grinscan.net/

### PR DESCRIPTION
**Pull request by stakervali**
- https://grinscan.net/ is not working, so I removed it.
- Added a series of articles from CryptoProfG
- Fixed some typos like Mimble Wimble => Mimblewimble
- Changed Exchange sample description 
    Template solution for exchanges consits  => An example implementation for testnet exchange that consists of

### CODE REVIEW

**Review by davidtavarez — APPROVED** [review]

**Comment by MCM-Mike** [comment]
Can you add https://grinexplorer.net/ to the list I know the github repo was added but this could replace it to have at lease one explorer online.

Does anyone know who runs https://grinscan.net/  and ask if he wants to shutdown or needs some help?

**Comment by stakervali** [comment]
> Can you add https://grinexplorer.net/ to the list I know the github repo was added but this could replace it to have at lease one explorer online.

I switched  first entry to  https://grinexplorer.net/  , previously https://github.com/mimblewimble/grin-explorer

**Comment by Anynomouss** [comment]
I kind of messed up by first committing some improvements myself, so I manually resolved and copied these improvements.
Thanks for the improvements @stakervali

**Comment by hendi** [comment]
> Does anyone know who runs https://grinscan.net/ and ask if he wants to shutdown or needs some help?

AFAIK jasper runs it. I've contacted him regarding grinscan a couple of months ago on keybase, but with no reply.

**Pull request closed without merging**
